
export const verses = [
  "\"Direi do Senhor: Ele é o meu refúgio e a minha fortaleza.\" - Salmos 91:2",
  "\"O Senhor é quem te guarda; o Senhor é a tua sombra.\" - Salmos 121:5",
  "\"O choro pode durar uma noite, mas a alegria vem pela manhã.\" - Salmos 30:5",
  "\"Vinde a mim, todos os que estais cansados e oprimidos.\" - Mateus 11:28",
  "\"Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.\" - 1 Pedro 5:7",
  "\"O Senhor está perto dos que têm o coração quebrantado.\" - Salmos 34:18",
  "\"Apascenta as minhas ovelhas.\" - João 21:17",
  "\"Não se turbe o vosso coração; credes em Deus, crede também em mim.\" - João 14:1",
  "\"Mil cairão ao teu lado, e dez mil à tua direita, mas não chegará a ti.\" - Salmos 91:7",
  "\"O Senhor é a minha luz e a minha salvação; a quem temerei?\" - Salmos 27:1",
  "\"Em paz me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.\" - Salmos 4:8",
  "\"Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.\" - Salmos 46:1",
  "\"Aquietai-vos, e sabei que eu sou Deus.\" - Salmos 46:10",
  "\"A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.\" - 2 Coríntios 12:9",
  "\"O Senhor é o meu pastor, nada me faltará.\" - Salmos 23:1",
  "\"Certamente que a bondade e a misericórdia me seguirão todos os dias.\" - Salmos 23:6",
  "\"Ele fortalece ao cansado e dá grande vigor ao que está sem forças.\" - Isaías 40:29",
  "\"Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.\" - Isaías 41:10",
  "\"O Senhor é bom, uma fortaleza no dia da angústia.\" - Naum 1:7",
  "\"O meu socorro vem do Senhor que fez o céu e a terra.\" - Salmos 121:2",
  "\"Porque para Deus nada é impossível.\" - Lucas 1:37",
  "\"Deus enxugará de seus olhos toda lágrima.\" - Apocalipse 21:4",
  "\"A paz de Deus, que excede todo o entendimento, guardará os vossos corações.\" - Filipenses 4:7",
  "\"Pois eu, o Senhor teu Deus, te tomo pela tua mão direita.\" - Isaías 41:13",
  "\"O Senhor pelejará por vós, e vós vos calareis.\" - Êxodo 14:14",
  "\"Em tudo dai graças, porque esta é a vontade de Deus.\" - 1 Tessalonicenses 5:18",
  "\"Grandes coisas fez o Senhor por nós, pelas quais estamos alegres.\" - Salmos 126:3",
  "\"Este é o dia que fez o Senhor; regozijemo-nos, e alegremo-nos nele.\" - Salmos 118:24",
  "\"Deem graças ao Senhor, porque ele é bom; o seu amor dura para sempre.\" - Salmos 107:1",
  "\"Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios.\" - Salmos 103:2",
  "\"Cantarei ao Senhor enquanto eu viver; cantarei louvores ao meu Deus.\" - Salmos 104:33",
  "\"Alegrei-me quando me disseram: Vamos à casa do Senhor.\" - Salmos 122:1",
  "\"Tudo o que tem fôlego louve ao Senhor.\" - Salmos 150:6",
  "\"O meu coração exulta no Senhor.\" - 1 Samuel 2:1",
  "\"Graças a Deus, que nos dá a vitória por meio de nosso Senhor Jesus Cristo.\" - 1 Coríntios 15:57",
  "\"Ofereça a Deus sacrifício de louvor e pague os seus votos ao Altíssimo.\" - Salmos 50:14",
  "\"Bom é louvar ao Senhor, e cantar louvores ao teu nome, ó Altíssimo.\" - Salmos 92:1",
  "\"A tua misericórdia é melhor do que a vida; os meus lábios te louvarão.\" - Salmos 63:3",
  "\"Louvarei ao Senhor em todo o tempo; o seu louvor estará continuamente na minha boca.\" - Salmos 34:1",
  "\"Graças te dou, visto que por modo assombrosamente maravilhoso fui formado.\" - Salmos 139:14",
  "\"Quão preciosos são para mim, ó Deus, os teus pensamentos!\" - Salmos 139:17",
  "\"Ao Rei eterno, imortal, invisível, Deus único, seja honra e glória.\" - 1 Timóteo 1:17",
  "\"A minha alma engrandece ao Senhor.\" - Lucas 1:46",
  "\"Darei graças ao Senhor segundo a sua justiça.\" - Salmos 7:17",
  "\"Cantai ao Senhor um cântico novo.\" - Salmos 98:1",
  "\"Tu és o meu Deus; eu te darei graças.\" - Salmos 118:28",
  "\"Alegrem-se os céus, e regozije-se a terra.\" - 1 Crônicas 16:31",
  "\"Toda boa dádiva e todo dom perfeito vêm do alto.\" - Tiago 1:17",
  "\"O Senhor é a minha força e o meu escudo; nele confiou o meu coração.\" - Salmos 28:7",
  "\"Santo, Santo, Santo é o Senhor dos Exércitos.\" - Isaías 6:3",
  "\"Não to mandei eu? Sê forte e corajoso.\" - Josué 1:9",
  "\"Tudo posso naquele que me fortalece.\" - Filipenses 4:13",
  "\"Se Deus é por nós, quem será contra nós?\" - Romanos 8:31",
  "\"Mas os que esperam no Senhor renovarão as forças.\" - Isaías 40:31",
  "\"Combati o bom combate, acabei a carreira, guardei a fé.\" - 2 Timóteo 4:7",
  "\"A fé é o firme fundamento das coisas que se esperam.\" - Hebreus 11:1",
  "\"Porque vivemos por fé, e não pelo que vemos.\" - 2 Coríntios 5:7",
  "\"Resisti ao diabo, e ele fugirá de vós.\" - Tiago 4:7",
  "\"Aquele que começou a boa obra em vós a aperfeiçoará.\" - Filipenses 1:6",
  "\"O justo viverá pela fé.\" - Romanos 1:17",
  "\"Espera no Senhor, anima-te, e ele fortalecerá o teu coração.\" - Salmos 27:14",
  "\"Mil cairão ao teu lado, mas tu não serás atingido.\" - Salmos 91:7",
  "\"Embora eu ande pelo vale da sombra da morte, não temerei mal algum.\" - Salmos 23:4",
  "\"Não nos cansemos de fazer o bem, pois no tempo próprio colheremos.\" - Gálatas 6:9",
  "\"Se tiverdes fé como um grão de mostarda, nada vos será impossível.\" - Mateus 17:20",
  "\"Pedi, e dar-se-vos-á; buscai, e encontrareis; batei, e abrir-se-vos-á.\" - Mateus 7:7",
  "\"Sê fiel até à morte, e dar-te-ei a coroa da vida.\" - Apocalipse 2:10",
  "\"Aquele que crê em mim, ainda que esteja morto, viverá.\" - João 11:25",
  "\"O Senhor é a força da minha vida; de quem me recearei?\" - Salmos 27:1",
  "\"Pela graça sois salvos, por meio da fé.\" - Efésios 2:8",
  "\"Para Deus tudo é possível.\" - Mateus 19:26",
  "\"Ao que crê, tudo é possível.\" - Marcos 9:23",
  "\"Nesta batalha não tereis que pelejar; parai, estai em pé, e vede a salvação.\" - 2 Crônicas 20:17",
  "\"Os que confiam no Senhor serão como o monte Sião, que não se abala.\" - Salmos 125:1",
  "\"Eu sou o caminho, e a verdade e a vida.\" - João 14:6",
  "\"O temor do Senhor é o princípio da sabedoria.\" - Provérbios 1:7",
  "\"Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento.\" - Provérbios 3:5",
  "\"Lâmpada para os meus pés é tua palavra, e luz para o meu caminho.\" - Salmos 119:105",
  "\"O coração alegre aformoseia o rosto.\" - Provérbios 15:13",
  "\"A resposta branda desvia o furor, mas a palavra dura suscita a ira.\" - Provérbios 15:1",
  "\"Ensina-nos a contar os nossos dias, para que alcancemos coração sábio.\" - Salmos 90:12",
  "\"Buscai primeiro o Reino de Deus, e todas estas coisas vos serão acrescentadas.\" - Mateus 6:33",
  "\"O que ganha almas sábio é.\" - Provérbios 11:30",
  "\"Tudo tem o seu tempo determinado, e há tempo para todo o propósito.\" - Eclesiastes 3:1",
  "\"Amai-vos uns aos outros, como eu vos amei.\" - João 15:12",
  "\"Honra a teu pai e a tua mãe.\" - Êxodo 20:12",
  "\"A palavra do Senhor permanece para sempre.\" - 1 Pedro 1:25",
  "\"Vós sois o sal da terra e a luz do mundo.\" - Mateus 5:13-14",
  "\"Fazei tudo para a glória de Deus.\" - 1 Coríntios 10:31",
  "\"Não amemos de palavra, nem de língua, mas por obra e em verdade.\" - 1 João 3:18",
  "\"Guarda o teu coração, porque dele procedem as fontes da vida.\" - Provérbios 4:23",
  "\"Deus é amor; e quem está em amor está em Deus.\" - 1 João 4:16",
  "\"Sede cumpridores da palavra, e não somente ouvintes.\" - Tiago 1:22",
  "\"A língua dos sábios adorna o conhecimento.\" - Provérbios 15:2",
  "\"Bem-aventurados os limpos de coração, porque eles verão a Deus.\" - Mateus 5:8",
  "\"Onde estiver o vosso tesouro, aí estará também o vosso coração.\" - Mateus 6:21",
  "\"A sabedoria é melhor do que os rubis.\" - Provérbios 8:11",
  "\"A justiça exalta as nações.\" - Provérbios 14:34",
  "\"O que encobre as suas transgressões nunca prosperará.\" - Provérbios 28:13",
  "\"Seja o vosso falar: Sim, sim; Não, não.\" - Mateus 5:37"
];
